### ISSUE TITLE
Sms module

### ISSUE THREAD

**Issue by 6ixmediasa** [faizanje/Scan-it#1]
How do we enable the sms module

**Comment by faizanje** [comment]
From Settings Page -> Enable "Send SMS"

**Comment by faizanje** [comment]
SMS are being sent as soon as you scan the QR code. The phone number is supposed to be decoded from the QR code. The QR code must have a specific format separated by double hyphens (--)

**Comment by faizanje** [comment]
Closing it for now. Feel free to reopen it with more information.

**Comment by faizanje** [comment]
Closing it for now. Feel free to reopen it with more information.
